name: daily-build

on:
  schedule:
    - cron: '0 3 * * *'   # 毎日 12:00 JST 相当（03:00 UTC）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Init project (no deps needed)
        run: |
          npm init -y
          npm pkg set scripts.fallback="node scripts/fallback.mjs"
          npm pkg set scripts.sitemap="node scripts/build-sitemap.mjs"

      # ★ まずは確実に記事を出す（フォールバックだけ実行）
      - name: Generate fallback pages
        run: |
          npm run fallback || node scripts/fallback.mjs

      - name: Build sitemap
        run: |
          npm run sitemap || node scripts/build-sitemap.mjs

      - name: Commit & push
        run: |
          git config user.name "content-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "daily content (fallback): $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
