name: daily-build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'   # JST 12:00 相当（03:00 UTC）

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Smoke test
        run: echo "ok"
