name: daily-build

on:
  schedule:
    - cron: '0 3 * * *'  # 毎日 12:00 JST 相当（03:00 UTC）
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # ⚠ cache指定は外します（lockfileがないためアノテーションが出る）
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Prepare project
        run: |
          npm init -y
          npm pkg set scripts.generate="node scripts/generate.mjs"

      # Transformers.js を Node で動かすため onnxruntime-node を追加
      - name: Install deps (CPU)
        run: |
          npm install @xenova/transformers@2.17.2 onnxruntime-node@1.18.0

      - name: Generate pages with transformers.js (no API cost)
        env:
          TRANSFORMERS_CACHE: ./.cache
        run: |
          npm run generate

      - name: Build/refresh sitemap.xml
        run: |
          node -e "const fs=require('fs');const base='content';const files=fs.readdirSync(base).filter(f=>f.endsWith('.html'));let out='<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">\n';for(const f of files){out+=`<url><loc>https://s06659333-tech.github.io/niche/${base}/${f}</loc></url>\n`;}out+='</urlset>\n';fs.writeFileSync('sitemap.xml',out)"

      - name: Commit & push
        run: |
          git config user.name "content-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "daily content: $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push

