name: daily-build
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'   # JST 12:00(03:00 UTC)
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Generate fallback posts
        run: python3 scripts/generate_fallback.py

      - name: Build sitemap
        run: python3 scripts/build_sitemap.py

      - name: Commit & push
        run: |
          git config user.name "content-bot"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "daily fallback content: $(date -u +'%Y-%m-%d')" || echo "No changes"
          git push
